name: Di hola

on:
  push:
    branches:
      - main

jobs:
  hola:
    runs-on: ubuntu-18.04
    steps:
      - name: Di hola
        run: |
          echo "Multiline commands can be used with a pipe."
          echo "El tiempo es $(date)."
      - name: Fecha
        run: date
      - run: ls -l