name: Deployment pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                    fetch-depth: 0
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - name: Install dependencies
              run: npm install --no-audit --no-fund --no-optional
            - name: Lint project
              run: npm run eslint
            - name: Build project
              run: npm run build
            - name: Test project
              run: npm run test
            - name: E2E Tests
              uses: cypress-io/github-action@v2
              with:
                    command: npm run test:e2e
                    start: npm run start-test
                    wait-on: 'http://localhost:5000'
            - name: 'Deploy to Netlify'
              if: ${{ github.event_name == 'push' }}
              uses: jsmrcaga/action-netlify-deploy@v2.0.0
              with:
                NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                NETLIFY_DEPLOY_TO_PROD: true
                deploy_alias: ${{ env.BRANCH_NAME }}
                build_directory: dist
            